### ISSUE TITLE
Missing implementation for `add_tool`

### ISSUE THREAD

**Issue by jlia0** [lmnr-ai/flow#3]
The source code does not contain `add_tool `.

**Comment by skull8888888** [comment]
@jlia0 not sure what you mean by that? Can you please elaborate more?

**Comment by jlia0** [comment]
> @jlia0 not sure what you mean by that? Can you please elaborate more?

Simple AI Agent tool usage
```
def my_tool(context: Context) -> TaskOutput:
    return TaskOutput(output="result")

flow.add_tool("my_tool", my_tool)
```

In the above example -- `flow.add_tool("my_tool", my_tool)`

However, there isn't an `add_tool` method in the source code in https://github.com/lmnr-ai/flow/blob/main/src/lmnr_flow/flow.py

**Comment by skull8888888** [comment]
oh, I started writing some example and totally forgot to finish it. add_tool function is just hallucination of a cursor :) Thank you for pointing it out! You can use any task as a tool for the agent. Just push it to the queue.

**Comment by jlia0** [comment]
Ohh that's funny lol... Also you might want to remove other hallucinations of `add_tool` in the readme.
